### ISSUE TITLE
Oscdimg not being recognized

### ISSUE THREAD

**Issue by ShadowCodeX-debug** [bravomail/tinier11#3]
Oscdimg is not being found in the folder in which the bat file is in.

## Steps on reproduction
1. Download repository and then download ADK installer.
2. Download the module with oscdimg in it.
3. Move oscdimg.exe to the unzipped repository folder.
4. Run the bat as admin.

## Expected Behavior
It to work. Not a "not found" error.

![image](https://github.com/bravomail/tinier11/assets/93408587/16e36cef-5ded-4170-90bb-a36c3c192255)

## Desktop Info
 - OS: Windows 11 Home
 - Browser: Opera
 - Version: 22H2(?)

## Additional
I used the amd64 version of oscdimg

**Comment by bravomail** [comment]
I commited the change to main fork. Test it. I already did. Thanks for finding this issue!

**Comment by ShadowCodeX-debug** [comment]
Np

**Comment by ShadowCodeX-debug** [comment]
Update: It does work, this is solved 🔥

**Comment by bravomail** [comment]
Closing the issue
