### ISSUE TITLE
New WIndows version using install.esd instead of install.wim and tinier11 is not detecting it

### ISSUE THREAD

**Issue by sblmbb** [bravomail/tinier11#9]
**Describe the bug**
New WIndows version using install.esd instead of install.wim and tinier11 is not detecting it

**Comment by bravomail** [comment]
ye, it's been that way for a while. Microsoft packs wim into ESD. So, you need to use websites like uupdump, which keep chaging it's DNS name.  at the moment it's uupdump.net

**Comment by bravomail** [comment]
closing the issue.
